In [ ]:
import matplotlib as mpl
import matplotlib.pyplot as plt

import networkx as nx
import numpy as np
import pandas as pd

import sys
sys.path.append('../src/')
import visJS_module

import imp
imp.reload(visJS_module)

In [ ]:

G = nx.connected_watts_strogatz_graph(30,5,.2)
nodes = G.nodes()
edges = G.edges()

In [ ]:

cc = nx.clustering(G)
degree = G.degree()
bc = nx.betweenness_centrality(G)
nx.set_node_attributes(G,'clustering_coefficient',cc)
nx.set_node_attributes(G,'degree',degree)
nx.set_node_attributes(G,'betweenness_centrality',bc)

In [ ]:

node_to_color = visJS_module.return_node_to_color(G,field_to_map='betweenness_centrality',cmap=mpl.cm.spring_r,alpha = 1,
                                                 color_max_frac = .9,color_min_frac = .1)

pos = nx.spring_layout(G)

nodes_dict = [{"id":n,"color":node_to_color[n],
               "degree":nx.degree(G,n),
              "x":pos[n][0]*1000,
              "y":pos[n][1]*1000} for n in nodes
              ]
node_map = dict(zip(nodes,range(len(nodes))))  # map to indices for source/target in edges
edges_dict = [{"source":node_map[edges[i][0]], "target":node_map[edges[i][1]], 
              "color":"gray","title":'test'} for i in range(len(edges))]

visJS_module.visjs_network(nodes_dict,edges_dict,time_stamp=1,
                          node_size_multiplier=7,
                          node_size_transform = '',
                          node_color_highlight_border='red',
                          node_color_highlight_background='#D3918B',
                          node_color_hover_border='blue',
                          node_color_hover_background='#8BADD3',
                          node_font_size=25,
                          edge_arrow_to=True,
                          physics_enabled=True,
                          edge_color_highlight='#8A324E',
                          edge_color_hover='#8BADD3',
                          edge_width=3,
                          max_velocity=15,
                          min_velocity=1)

In [7]:
import numpy as np
import itertools

posArgs= [0,1]      # 0->1 / 1->1 is not allowed..neither is 0->1
negArgs= [2]

nargs= len(posArgs+ negArgs)
allPermutations= np.array(list(itertools.product([0,1], repeat=nargs*nargs)))

# Create list of Attacks that we will never need. Circular attacks, and attacks between arguments of same polarity
circularAttacks = (np.arange(0, nargs*nargs, nargs+1)).tolist()
samePolarityAttacks = []
posList = list(itertools.permutations(posArgs, 2))
negList = list(itertools.permutations(negArgs, 2))
totList = posList + negList

for l in totList:
    ptn = ((l[0]+1)*nargs)- ((nargs+1) - l[1]) + 1 # All the odd +1 are to account for the shift in 0 index
    samePolarityAttacks.append(ptn)


graphsToDelete = np.unique([circularAttacks + samePolarityAttacks])
subGraphs = allPermutations[:,graphsToDelete]
cutDownGraphs = np.delete(allPermutations, (np.where(subGraphs>0)[0]).tolist(), axis = 0)

for graph in cutDownGraphs:
    singleGraph= np.vstack( np.array_split(np.array(graph), nargs))
    print(singleGraph)

512
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 1 0]]
[[0 0 0]
 [0 0 0]
 [1 0 0]]
[[0 0 0]
 [0 0 0]
 [1 1 0]]
[[0 0 0]
 [0 0 1]
 [0 0 0]]
[[0 0 0]
 [0 0 1]
 [0 1 0]]
[[0 0 0]
 [0 0 1]
 [1 0 0]]
[[0 0 0]
 [0 0 1]
 [1 1 0]]
[[0 0 1]
 [0 0 0]
 [0 0 0]]
[[0 0 1]
 [0 0 0]
 [0 1 0]]
[[0 0 1]
 [0 0 0]
 [1 0 0]]
[[0 0 1]
 [0 0 0]
 [1 1 0]]
[[0 0 1]
 [0 0 1]
 [0 0 0]]
[[0 0 1]
 [0 0 1]
 [0 1 0]]
[[0 0 1]
 [0 0 1]
 [1 0 0]]
[[0 0 1]
 [0 0 1]
 [1 1 0]]


In [12]:
a = [0,1]
b = [2]
c = list(itertools.chain.from_iterable([a,b]))
print(c)

[0, 1, 2]


In [18]:
import json

with open('allAnnotationsChutesRun1.json') as data_file:    
    data = json.load(data_file)
    
    for x in data:
        print(list(x))

['[']
['[']
['[']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['1']
[']']
[',']
['[']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['1']
[']']
[',']
['[']
['0']
[',']
['0']
[',']
['1']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[']']
[',']
['[']
['0']
[',']
['0']
[',']
['1']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[']']
[',']
['[']
['0']
[',']
['0']
[',']
['1']
[',']
['0']
[',']
['1']
[',']
['0']
[',']
['0']
[']']
[',']
['n']
['u']
['l']
['l']
[',']
['[']
['0']
[',']
['0']
[',']
['1']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[']']
[',']
['[']
['1']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[']']
[']']
[',']
['[']
['[']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['1']
[']']
[',']
['[']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['1']
[']']
[',']
['[']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['0']
[',']
['1'